Repository prgrms-web-devcourse/Team-JJINSA-HyperLink-FE, pull requests merged in 2023-04, with the labels that each got.

#286 back to top fab에 툴팁 적용
  src/components/backToTop/index.tsx
Labels: ☀ Feature

#292 어드민 페이지 테이블 버그
  src/components/admin/companies/index.tsx
  src/components/admin/contents/index.tsx
  src/components/admin/creators/index.tsx
Labels: 🛠 Fix

#294 콘텐츠 리스트, 크리에이터 추천 반응형 추가
  src/components/cardItem/content/cardBottom/index.tsx
  src/components/cardItem/content/cardBottom/style.css.ts
  src/components/cardList/style.css.ts
  src/components/common/slider/style.css.ts
  src/pages/home/index.tsx
  src/pages/home/style.css.ts
Labels: 🔨 Refactor

#296 헤더 반응형
  src/components/common/header/SearchBar.tsx
  src/components/common/header/index.tsx
  src/components/common/header/style.css.ts
  src/components/common/header/userNav/Authorized.tsx
  src/components/common/icon/index.tsx
  src/components/common/icon/style.css.ts
  src/components/common/modal/style.css.ts
  src/components/main/style.css.ts
  src/components/modal/category/style.css.ts
  src/components/signup/style.css.ts
  src/pages/home/index.tsx
  src/stores/searchBar.ts
  src/styles/keyframes.css.ts
Labels: ☀ Feature

#298 랜딩 페이지 모바일 스크롤
  src/pages/home/index.tsx
  src/utils/optimization/throttle.ts
Labels: 🔨 Refactor

#300 텍스트 툴팁 ellipsis된 경우에만 적용
  src/components/admin/contents/index.tsx
  src/components/admin/creators/index.tsx
  src/components/cardItem/content/cardBottom/index.tsx
  src/components/cardItem/creator/index.tsx
  src/components/common/tooltip/index.tsx
Labels: 🔨 Refactor

#301 크리에이터 목록 반응형 추가
  src/components/buttonGroup/style.css.ts
  src/components/cardList/style.css.ts
  src/pages/creatorDetail/style.css.ts
  src/pages/creatorList/style.css.ts
Labels: 🔨 Refactor

#304 오늘의 하이퍼 링크 페이지 반응형 수정
  src/components/dailyBriefing/style.css.ts
  src/pages/dailyBriefing/style.css.ts
Labels: 🔨 Refactor
