Repository prgrms-web-devcourse/Team-JJINSA-HyperLink-FE, pull requests merged in 2023-03, with the labels that each got.

#67 콘텐츠 검색 기능 구현
  src/App.tsx
  src/__mocks__/handlers/contents.ts
  src/__mocks__/handlers/index.ts
  src/__mocks__/worker.ts
  src/api/contents.ts
  src/components/cardItem/article/cardBottom/index.tsx
  src/components/cardItem/article/index.tsx
  src/components/common/header/SearchBar.tsx
  src/components/common/input/index.tsx
  src/components/common/spinner/index.tsx
  src/components/common/spinner/style.css.ts
  src/pages/index.ts
  src/pages/searchResult/index.tsx
  src/pages/searchResult/style.css.ts
  src/types/contents.ts
Labels: 리뷰 요청, ☀ Feature, 🌐 MSW

#68 card list 구현 및 msw 연동
  src/__mocks__/Dummy.ts
  src/__mocks__/handlers/cardlist.ts
  src/__mocks__/handlers/index.ts
  src/__mocks__/worker.ts
  src/api/cardlist.ts
  src/components/cardItem/article/banner/bannerAvatar/index.tsx
  src/components/cardItem/article/banner/bannerAvatar/style.css.ts
  src/components/cardItem/article/banner/bannerText/index.tsx
  src/components/cardItem/article/banner/bannerText/style.css.ts
  src/components/cardItem/article/cardBottom/index.tsx
  src/components/cardItem/article/cardBottom/style.css.ts
  src/components/cardItem/article/cardTop/index.tsx
  src/components/cardItem/article/style.css.ts
  src/components/cardList/index.tsx
  src/components/cardList/style.css.ts
  src/components/common/card/style.css.ts
  src/main.tsx
  src/pages/home.tsx
Labels: ☀ Feature, 🌐 MSW

#74 배너 애니메이션 컴포넌트 구현
  package.json
  src/components/common/banner/index.tsx
  src/components/common/banner/positions.tsx
  src/components/common/banner/style.css.ts
  src/components/common/index.ts
  src/components/modal/login/index.tsx
  src/components/modal/login/style.css.ts
  src/stories/components/common/Banner.stories.tsx
  yarn.lock
Labels: ☀ Feature

#70 404 페이지 구현
  src/App.tsx
  src/assets/alert.svg
  src/pages/index.ts
  src/pages/notFound/index.tsx
  src/pages/notFound/style.css.ts
  src/styles/tokens.css.ts
Labels: 리뷰 요청, ☀ Feature

#77 검색 페이지 UI 수정
  src/__mocks__/Dummy.ts
  src/components/cardItem/article/cardBottom/index.tsx
  src/pages/searchResult/index.tsx
  src/pages/searchResult/style.css.ts
Labels: 🎨 Design, 🔨 Refactor

#80 article 카드 content 카드로 변경, types/contents.ts 적용, 반응형 버그 수정
  src/__mocks__/Dummy.ts
  src/__mocks__/handlers/contents.ts
  src/__mocks__/worker.ts
  src/api/cardlist.ts
  src/components/cardItem/content/CardModal.tsx
  src/components/cardItem/content/banner/bannerAvatar/index.tsx
  src/components/cardItem/content/banner/bannerAvatar/style.css.ts
  src/components/cardItem/content/banner/bannerText/index.tsx
  src/components/cardItem/content/banner/bannerText/style.css.ts
  src/components/cardItem/content/cardBottom/index.tsx
  src/components/cardItem/content/cardBottom/style.css.ts
  src/components/cardItem/content/cardTop/index.tsx
  src/components/cardItem/content/cardTop/style.css.ts
  src/components/cardItem/content/index.tsx
  src/components/cardItem/content/style.css.ts
  src/components/cardItem/creator/index.tsx
  src/components/cardItem/creator/style.css.ts
  src/components/cardList/index.tsx
  src/components/cardList/style.css.ts
  src/components/common/card/index.tsx
  src/components/common/card/style.css.ts
  src/pages/home.tsx
  src/stories/components/common/Card.stories.tsx
Labels: 🛠 Fix, 🔨 Refactor

#82 내 정보 페이지 구현
  src/App.tsx
  src/components/myPage/MyInfo.tsx
  src/components/myPage/index.ts
  src/components/myPage/style.css.ts
  src/pages/index.ts
  src/pages/myPage/index.tsx
  src/pages/myPage/style.css.ts
  src/types/myInfo.ts
Labels: ☀ Feature, 🌐 MSW

#87 홈 페이지 스크롤 전 화면 구현
  src/App.tsx
  src/api/core.ts
  src/components/common/banner/style.css.ts
  src/components/common/header/SearchBar.tsx
  src/components/common/header/index.tsx
  src/components/common/header/style.css.ts
  src/components/common/input/style.css.ts
  src/components/main/index.tsx
  src/components/main/style.css.ts
  src/pages/home.tsx
  src/pages/home/index.tsx
  src/pages/home/style.css.ts
  src/pages/index.ts
  src/stores/scroll.ts
  src/styles/global.css.ts
Labels: 리뷰 요청, ☀ Feature, 🎨 Design

#83 유저 드롭다운 구현
  src/api/member.ts
  src/components/common/avatar/index.tsx
  src/components/common/header/UserNav.tsx
  src/components/common/header/style.css.ts
  src/components/common/modal/index.tsx
  src/components/common/modal/style.css.ts
  src/components/modal/myInfo/index.tsx
  src/components/modal/myInfo/style.css.ts
  src/main.tsx
  src/stores/modal.ts
Labels: 리뷰 요청, ☀ Feature, 🎨 Design, 🌐 MSW

#85 axios 환경 설정
  src/api/core.ts
Labels: 👩‍🌾 Chore

#92 react-query, suspense 관련 에러 해결
  src/api/core.ts
  src/components/common/header/UserNav.tsx
  src/components/layout/index.tsx
  src/components/modal/index.ts
  src/components/modal/myInfo/index.tsx
  src/main.tsx
  src/pages/home/index.tsx
  src/pages/searchResult/index.tsx
  src/styles/global.css.ts
Labels: 🛠 Fix, 🐛 Bug

#90 내 정보 페이지 이미지 업로드 기능
  src/components/common/avatar/index.tsx
  src/components/myPage/MyInfo.tsx
  src/components/myPage/style.css.ts
Labels: ☀ Feature

#89 검색 결과 페이지 UI 구현
  src/App.tsx
  src/pages/searchResult/index.tsx
  src/pages/searchResult/style.css.ts
Labels: 🎨 Design

#99 홈 페이지 스크롤 전 화면 배너 초기 사이징
  src/components/main/index.tsx
Labels: 🛠 Fix

#101 홈 페이지 스크롤 애니메이션 최적화
  src/pages/home/index.tsx
  src/utils/optimization/throttle.ts
Labels: 🔨 Refactor

#97 소속 회사 인증 모달 구현
  src/components/modal/certification/index.tsx
  src/components/modal/certification/style.css.ts
Labels: ☀ Feature

#104 auth 로직 dto와 맞추기
  src/__mocks__/handlers/auth.ts
  src/api/auth.ts
  src/components/modal/login/index.tsx
  src/pages/sigunup/index.tsx
Labels: 🔨 Refactor

#109 1차 배포
  public/assets/alert.svg
  public/assets/defaultProfileImage.png
  public/assets/googleLogo.png
  public/assets/logo.svg
  public/assets/react.svg
  public/assets/user.svg
  public/favicon.ico
  src/components/cardItem/content/banner/bannerAvatar/index.tsx
  src/components/cardItem/content/banner/bannerText/index.tsx
  src/components/common/avatar/index.tsx
  src/components/common/header/UserNav.tsx
  src/components/common/header/index.tsx
  src/components/modal/login/index.tsx
  src/pages/notFound/index.tsx
Labels: 👑 Deploy

#107 관심 카테고리 모달 구현
  src/components/modal/category/index.tsx
  src/components/modal/category/style.css.ts
Labels: ☀ Feature

#116 career dto 맞추기
  src/utils/constants/signup.ts
Labels: ☀ Feature, 🔨 Refactor

#117 silent refresh 성공 시만 auth 설정
  src/components/layout/index.tsx
Labels: 🛠 Fix, 👑 Deploy

#114 메인 콘텐츠, 검색 콘텐츠 무한 스크롤 기능 구현
  index.html
  package.json
  src/__mocks__/data.ts
  src/__mocks__/handlers/cardlist.ts
  src/__mocks__/handlers/index.ts
  src/__mocks__/handlers/mainContents.ts
  src/__mocks__/handlers/searchContents.ts
  src/__mocks__/worker.ts
  src/api/cardlist.ts
  src/api/contents.ts
  src/api/mainContents.ts
  src/api/searchContents.ts
  src/components/cardList/index.tsx
  src/components/common/avatar/index.tsx
  src/components/common/header/UserNav.tsx
  src/components/common/header/index.tsx
  src/components/mainContents/index.tsx
  src/components/mainContents/style.css.ts
  src/components/modal/category/style.css.ts
  src/hooks/infiniteQuery/useMainContentsInfinitelQuery.ts
  src/hooks/infiniteQuery/useSearchContentsInfiniteQuery.ts
  src/pages/home/index.tsx
  src/pages/home/style.css.ts
  src/pages/searchResult/index.tsx
  src/pages/searchResult/style.css.ts
  src/stores/selectedCategory.ts
  yarn.lock
Labels: ☀ Feature

#113 특정 크리에이터 페이지 UI 구현
  src/App.tsx
  src/components/common/button/style.css.ts
  src/pages/creatorDetail/index.tsx
  src/pages/creatorDetail/style.css.ts
  src/pages/index.ts
Labels: 리뷰 요청, 🎨 Design

#119 폴더명 오타 수정
  src/pages/index.ts
  src/pages/signup/index.tsx
  src/pages/signup/style.css.ts
  yarn.lock
Labels: ✏ Rename

#122 카테고리 버튼 그룹 구현 및 각 페이지 카테고리 별 데이터 연동
  index.html
  src/App.tsx
  src/__mocks__/handlers/index.ts
  src/__mocks__/handlers/specificCreator.ts
  src/__mocks__/worker.ts
  src/api/specificCreator.ts
  src/components/buttonGroup/index.tsx
  src/components/buttonGroup/style.css.ts
  src/components/cardItem/content/cardBottom/index.tsx
  src/components/common/avatar/index.tsx
  src/components/mainContents/index.tsx
  src/components/modal/myInfo/index.tsx
  src/hooks/infiniteQuery/useSpecificCreatorInfiniteQuery.ts
  src/pages/creatorDetail/index.tsx
  src/pages/home/index.tsx
Labels: ☀ Feature, 🔨 Refactor, 🌐 MSW

#123 어드민 페이지 라우팅
  src/App.tsx
  src/__mocks__/handlers/auth.ts
  src/api/auth.ts
  src/components/layout/index.tsx
  src/components/modal/login/index.tsx
  src/components/modal/myInfo/index.tsx
  src/pages/admin/index.tsx
  src/pages/index.ts
  src/stores/auth.ts
Labels: 리뷰 요청, ☀ Feature

#131 어드민 페이지 api 정의 및 msw 정의
  src/__mocks__/handlers/admin.ts
  src/api/admin.ts
Labels: 리뷰 요청, ☀ Feature, 🌐 MSW

#136 관심 카테고리 모달 msw 연동
  src/api/member.ts
  src/components/common/header/UserNav.tsx
  src/components/modal/category/index.tsx
  src/components/modal/category/style.css.ts
  src/components/modal/index.ts
  src/stores/modal.ts
Labels: ☀ Feature

#140 카테고리별 조회수 api 추가 및 type 분리
  src/__mocks__/handlers/admin.ts
  src/api/admin.ts
  src/types/admin.ts
Labels: ☀ Feature, 🌐 MSW

#127 데일리 브리핑 페이지 UI 구현
  package.json
  src/App.tsx
  src/components/common/card/index.tsx
  src/components/common/card/style.css.ts
  src/components/common/header/index.tsx
  src/components/common/icon/index.tsx
  src/components/common/icon/style.css.ts
  src/components/dailyBriefing/CategoryChart.tsx
  src/components/dailyBriefing/ContentsCountChart.tsx
  src/components/dailyBriefing/Ranking.tsx
  src/components/dailyBriefing/Summary.tsx
  src/components/dailyBriefing/style.css.ts
  src/pages/dailyBriefing/index.tsx
  src/pages/dailyBriefing/style.css.ts
  src/pages/index.ts
  src/styles/global.css.ts
  src/styles/tokens.css.ts
  src/utils/constants/categories.ts
  yarn.lock
Labels: 리뷰 요청, 🎨 Design

#129 dropdown 컴포넌트에 가로 스크롤 없애기
  src/components/common/dropdown/style.css.ts
Labels: 🛠 Fix

#139 내 정보 API 연동
  src/api/member.ts
  src/components/common/header/CountDown.tsx
  src/components/common/header/UserNav.tsx
  src/components/common/header/index.tsx
  src/components/common/header/style.css.ts
  src/components/common/header/userNav/Authorized.tsx
  src/components/common/header/userNav/index.tsx
  src/components/modal/myInfo/index.tsx
  src/types/myInfo.ts
Labels: 리뷰 요청, ☀ Feature, 🌎 API

#141 메인 페이지 탭 state 추가
  src/components/common/header/index.tsx
  src/stores/tab.ts
Labels: ☀ Feature

#134 크리에이터 목록 페이지 구현
  src/App.tsx
  src/__mocks__/handlers/creatorList.ts
  src/__mocks__/handlers/index.ts
  src/__mocks__/worker.ts
  src/api/creatorList.ts
  src/components/cardItem/content/cardBottom/index.tsx
  src/components/cardItem/creator/index.tsx
  src/components/cardItem/creator/style.css.ts
  src/components/cardList/index.tsx
  src/components/cardList/style.css.ts
  src/components/common/card/style.css.ts
  src/components/common/header/style.css.ts
  src/components/mainContents/index.tsx
  src/hooks/infiniteQuery/useCreatorListInfiniteQuery.ts
  src/pages/creatorDetail/index.tsx
  src/pages/creatorList/index.tsx
  src/pages/creatorList/style.css.ts
  src/pages/index.ts
  src/pages/searchResult/index.tsx
  src/types/contents.ts
Labels: ☀ Feature

#147 메인 페이지 카드 리스트 API 연동
  src/api/bookmark.ts
  src/api/like.ts
  src/api/mainContents.ts
  src/api/notRecommend.ts
  src/api/searchContents.ts
  src/api/view.ts
  src/components/cardItem/content/banner/bannerAvatar/index.tsx
  src/components/cardItem/content/banner/bannerText/index.tsx
  src/components/cardItem/content/cardBottom/index.tsx
  src/components/cardItem/content/cardTop/index.tsx
  src/components/cardItem/content/cardTop/style.css.ts
  src/components/cardItem/content/index.tsx
  src/components/mainContents/index.tsx
  src/hooks/infiniteQuery/useCreatorListInfiniteQuery.ts
  src/hooks/infiniteQuery/useMainContentsInfinitelQuery.ts
  src/types/contents.ts
Labels: 리뷰 요청, ☀ Feature, 🌎 API

#153 merge 충돌 버그 수정
  src/components/common/header/index.tsx
  src/pages/index.ts
Labels: 🐛 Bug, 🔥 HurryUp

#148 프로필 수정 api 연동
  src/api/member.ts
  src/components/myPage/MyInfo.tsx
Labels: ☀ Feature, 🌎 API

#154 프로필 이미지 수정 api 연동
  package.json
  src/api/member.ts
  src/api/s3Image.ts
  src/components/myPage/MyInfo.tsx
  vite.config.ts
  yarn.lock
Labels: 리뷰 요청, ☀ Feature, 🌎 API

#155 어드민 페이지 UI 구현
  src/__mocks__/handlers/admin.ts
  src/__mocks__/handlers/index.ts
  src/__mocks__/handlers/member.ts
  src/__mocks__/worker.ts
  src/api/admin.ts
  src/api/member.ts
  src/components/admin/addCreator/index.tsx
  src/components/admin/addCreator/style.css.ts
  src/components/admin/contents/index.tsx
  src/components/admin/contents/style.css.ts
  src/components/admin/creators/index.tsx
  src/components/admin/creators/style.css.ts
  src/components/admin/index.tsx
  src/components/admin/weeklyViews/index.tsx
  src/components/admin/weeklyViews/style.css.ts
  src/components/common/dropdown/index.tsx
  src/components/common/dropdown/style.css.ts
  src/components/common/header/userNav/NotAuthorized.tsx
  src/components/common/index.ts
  src/components/common/table/index.tsx
  src/components/common/table/style.css.ts
  src/components/myPage/MyInfo.tsx
  src/pages/admin/index.tsx
  src/pages/admin/style.css.ts
  src/styles/global.css.ts
  src/styles/tokens.css.ts
  src/utils/color.ts
  src/utils/constants/category.ts
  src/utils/date.ts
  src/utils/object.ts
  src/utils/storage.ts
Labels: 리뷰 요청, 🎨 Design

#158 중복 선언 제거
  src/api/member.ts
Labels: 🛠 Fix

#146 검색 api 연동
  src/__mocks__/handlers/searchContents.ts
  src/api/searchContents.ts
  src/types/contents.ts
Labels: 리뷰 요청, ☀ Feature, 🌎 API

#163 divider 컴포넌트 스타일 수정
  src/components/common/divider/style.css.ts
Labels: 🎨 Design

#167 관심 카테고리 msw 연동
  src/__mocks__/handlers/attentionCategory.ts
  src/__mocks__/handlers/index.ts
  src/__mocks__/worker.ts
  src/api/attentionCategory.ts
  src/components/common/header/userNav/Authorized.tsx
  src/components/modal/category/index.tsx
  src/components/modal/category/style.css.ts
Labels: ☀ Feature, 🌐 MSW

#169 특정 크리에이터 상세 정보 msw 연동
  src/__mocks__/handlers/creator.ts
  src/__mocks__/handlers/index.ts
  src/__mocks__/worker.ts
  src/api/creator.ts
  src/pages/creatorDetail/index.tsx
Labels: ☀ Feature, 🌐 MSW

#165 어드민 페이지 msw 연동
  src/__mocks__/handlers/admin.ts
  src/components/admin/addCreator/index.tsx
  src/components/admin/contents/index.tsx
  src/components/admin/contents/style.css.ts
  src/components/admin/creators/index.tsx
  src/components/admin/weeklyViews/index.tsx
  src/components/common/table/index.tsx
  src/components/common/table/style.css.ts
  src/pages/admin/index.tsx
Labels: ☀ Feature, 🌐 MSW

#178 유저 맞춤 추천 크리에이터 msw 연동
  src/__mocks__/handlers/index.ts
  src/__mocks__/handlers/recommendedCreators.ts
  src/__mocks__/worker.ts
  src/api/creator.ts
  src/components/common/card/style.css.ts
  src/components/common/slider/index.tsx
  src/components/common/slider/style.css.ts
  src/components/recommendedCreators/index.tsx
  src/pages/home/index.tsx
  src/types/contents.ts
Labels: 리뷰 요청, ☀ Feature, 🌐 MSW

#176 회사 이메일 인증 msw 연동 / api 연동
  src/__mocks__/handlers/companies.ts
  src/__mocks__/handlers/index.ts
  src/__mocks__/handlers/member.ts
  src/__mocks__/worker.ts
  src/api/companies.ts
  src/api/s3Image.ts
  src/components/admin/addCreator/index.tsx
  src/components/modal/certification/NotSendedView/index.tsx
  src/components/modal/certification/NotSendedView/style.css.ts
  src/components/modal/certification/SendedView/index.tsx
  src/components/modal/certification/SendedView/style.css.ts
  src/components/modal/certification/index.tsx
  src/components/modal/certification/style.css.ts
  src/components/myPage/MyInfo.tsx
  src/components/myPage/style.css.ts
  src/types/myInfo.ts
  src/utils/constants/signup.ts
Labels: ☀ Feature, 🌎 API, 🌐 MSW

#180 데일리 브리핑 페이지 msw, api 연동
  src/__mocks__/handlers/dailyBriefing.ts
  src/__mocks__/handlers/index.ts
  src/__mocks__/worker.ts
  src/api/dailyBriefing.ts
  src/components/.gitkeep
  src/components/dailyBriefing/CategoryChart.tsx
  src/components/dailyBriefing/ContentsCountChart.tsx
  src/components/dailyBriefing/Ranking.tsx
  src/components/dailyBriefing/Summary.tsx
  src/components/dailyBriefing/index.tsx
  src/pages/dailyBriefing/index.tsx
  src/pages/dailyBriefing/style.css.ts
  src/types/dailyBriefing.ts
  src/utils/constants/storage.ts
Labels: 리뷰 요청, ☀ Feature, 🌎 API, 🌐 MSW

#183 어드민 페이지 컨텐츠, 크리에이터 페이지네이션 구현
  src/__mocks__/handlers/admin.ts
  src/api/admin.ts
  src/components/admin/contents/index.tsx
  src/components/admin/contents/style.css.ts
  src/components/admin/creators/index.tsx
  src/components/admin/creators/style.css.ts
  src/components/admin/pagination/index.tsx
  src/components/admin/pagination/style.css.ts
  src/components/admin/weeklyViews/index.tsx
  src/components/admin/weeklyViews/style.css.ts
  src/components/common/header/index.tsx
  src/components/common/table/index.tsx
  src/components/common/table/style.css.ts
  src/pages/admin/index.tsx
  src/types/admin.ts
  src/utils/weeklyViews.ts
Labels: 리뷰 요청, ☀ Feature

#190 관심 카테고리 모달 관련 버그 수정
  src/__mocks__/handlers/attentionCategory.ts
  src/api/attentionCategory.ts
  src/components/common/header/userNav/Authorized.tsx
  src/components/modal/category/index.tsx
  src/components/modal/certification/SendedView/index.tsx
  src/components/modal/certification/SendedView/style.css.ts
  src/components/myPage/ErrorView/index.tsx
  src/components/myPage/ErrorView/style.css.ts
  src/components/myPage/MyInfo/index.tsx
  src/components/myPage/MyInfo/style.css.ts
  src/components/myPage/index.ts
  src/pages/myPage/index.tsx
Labels: 🛠 Fix

#193 s3 이미지 파일 삭제 구현
  src/api/s3Image.ts
Labels: ☀ Feature

#188 어드민 페이지 권한 없을 시 에러 페이지로 라우팅
  src/App.tsx
  src/pages/admin/index.tsx
  src/pages/error/index.tsx
  src/pages/error/style.css.ts
  src/pages/index.ts
Labels: ☀ Feature

#192 어드민 페이지 회사 추천 여부 보기, 변경 추가
  src/__mocks__/handlers/admin.ts
  src/api/admin.ts
  src/components/admin/companies/index.tsx
  src/components/admin/companies/style.css.ts
  src/components/admin/index.tsx
  src/pages/admin/index.tsx
  src/types/admin.ts
Labels: ☀ Feature

#196 내 정보 페이지 헤더 안 보이게 수정
  src/__mocks__/handlers/member.ts
  src/api/member.ts
  src/components/modal/category/index.tsx
  src/components/myPage/MyInfo/index.tsx
  src/pages/myPage/index.tsx
Labels: 🛠 Fix

#195 특정 크리에이터 페이지 API 연동 및 구독 기능 추가
  src/__mocks__/handlers/index.ts
  src/__mocks__/handlers/subscribe.ts
  src/api/creatorList.ts
  src/api/like.ts
  src/api/subscribe.ts
  src/components/cardItem/content/cardBottom/index.tsx
  src/components/cardItem/content/cardTop/index.tsx
  src/components/cardItem/content/index.tsx
  src/components/cardItem/creator/index.tsx
  src/components/common/avatar/index.tsx
  src/components/common/tab/index.tsx
  src/components/detailContents/creatorInfo/index.tsx
  src/components/detailContents/creatorInfo/style.css.ts
  src/components/detailContents/index.tsx
  src/components/mainContents/index.tsx
  src/components/modal/login/index.tsx
  src/hooks/infiniteQuery/useCreatorListInfiniteQuery.ts
  src/hooks/infiniteQuery/useSpecificCreatorInfiniteQuery.ts
  src/pages/creatorDetail/index.tsx
  src/pages/creatorList/index.tsx
  src/pages/creatorList/style.css.ts
  src/stores/lastTab.ts
Labels: ☀ Feature, 🌎 API

#199 페이지네이션 처음, 끝 이동 버튼 구현
  src/components/admin/contents/index.tsx
  src/components/admin/creators/index.tsx
  src/components/admin/pagination/index.tsx
Labels: ☀ Feature

#207 어드민 페이지 컨텐츠 카테고리별 조회수 일주일치로 변경
  src/__mocks__/handlers/admin.ts
  src/api/admin.ts
  src/components/admin/weeklyViews/index.tsx
  src/types/admin.ts
Labels: ☀ Feature

#214 어드민 페이지 회사 등록 구현
  src/__mocks__/handlers/admin.ts
  src/api/admin.ts
  src/components/admin/addCompany/index.tsx
  src/components/admin/addCompany/style.css.ts
  src/components/admin/companies/index.tsx
Labels: ☀ Feature

#211 관심 카테고리 한 개 이상 선택하도록 수정
  src/components/modal/category/index.tsx
Labels: 🛠 Fix

#217 카드 아이템 추천 배너 이미지 빈 값일 때, 로고 넣기
  src/components/cardItem/content/banner/bannerAvatar/index.tsx
Labels: 🔨 Refactor

#212 로그인 여부에 따른 추천 크리에이터
  src/pages/home/index.tsx
Labels: 🔨 Refactor

#201 어드민 페이지 이동시 nav 제거
  src/components/modal/myInfo/index.tsx
Labels: 🛠 Fix

#223 어드민 페이지 회사 이름 변경 추가
  src/__mocks__/handlers/admin.ts
  src/api/admin.ts
  src/components/admin/companies/companyName.tsx
  src/components/admin/companies/index.tsx
  src/components/common/input/index.tsx
Labels: 리뷰 요청, ☀ Feature

#220 조회수 페이지 여부에 따른 type 부여
  src/api/view.ts
  src/components/cardItem/content/banner/bannerAvatar/index.tsx
  src/components/cardItem/content/cardTop/index.tsx
  src/components/cardItem/content/index.tsx
  src/components/common/slider/style.css.ts
  src/hooks/infiniteQuery/useSearchContentsInfiniteQuery.ts
Labels: 🔨 Refactor

#202 데일리 브리핑 페이지에서 새로고침했을 때 헤더 사라지는 문제 해결하기
  src/components/common/header/index.tsx
  src/components/dailyBriefing/Summary.tsx
  src/pages/dailyBriefing/index.tsx
Labels: 리뷰 요청, 🛠 Fix

#226 어드민 페이지 s3 이미지 삭제 연동
  src/__mocks__/handlers/admin.ts
  src/components/admin/addCompany/index.tsx
  src/components/admin/addCreator/index.tsx
  src/components/admin/creators/index.tsx
  src/types/admin.ts
Labels: 리뷰 요청, ☀ Feature

#231 globall css 설정 변경
  vite.config.ts
Labels: 🔥 HurryUp

#205 fix: 프로필 이미지 변경시 헤더 이미지 안 바뀌는 버그 수정
  src/components/common/header/userNav/Authorized.tsx
  src/components/modal/myInfo/index.tsx
  src/components/myPage/MyInfo/index.tsx
Labels: 🛠 Fix

#221 검색 결과 페이지에서 새로고침했을 때 헤더 사라지는 문제 해결
  src/components/common/header/SearchBar.tsx
  src/components/searchResult/searchInfo.tsx
  src/components/searchResult/style.css.ts
  src/pages/searchResult/index.tsx
  src/pages/searchResult/style.css.ts
Labels: 🛠 Fix

#222 메인 페이지로 뒤로가기 시, api 호출 에러 수정 및 배너 화면에서 탭 제거
  src/components/cardItem/creator/index.tsx
  src/components/common/header/index.tsx
  src/components/common/tab/index.tsx
  src/components/mainContents/index.tsx
  src/pages/creatorList/index.tsx
  src/stores/lastTab.ts
Labels: 🛠 Fix, 🐛 Bug

#232 데일리 브리핑 수정된 api 반영
  src/__mocks__/handlers/dailyBriefing.ts
  src/components/dailyBriefing/ContentsCountChart.tsx
  src/components/dailyBriefing/Summary.tsx
  src/pages/dailyBriefing/index.tsx
  src/types/.gitkeep
  src/types/dailyBriefing.ts
  src/utils/constants/storage.ts
Labels: 리뷰 요청, ☀ Feature, 🌎 API

#233 소속 인증 모달 버그 수정
  src/__mocks__/handlers/companies.ts
  src/api/companies.ts
  src/components/modal/certification/NotSendedView/index.tsx
  src/components/modal/certification/SendedView/index.tsx
  src/components/modal/certification/SendedView/style.css.ts
  src/components/modal/certification/index.tsx
Labels: 🛠 Fix

#237 프로필 수정 관련 버그 수정
  src/__mocks__/handlers/recommendedCreators.ts
  src/components/common/header/userNav/Authorized.tsx
  src/components/modal/category/index.tsx
  src/components/modal/certification/NotSendedView/index.tsx
  src/components/modal/certification/NotSendedView/style.css.ts
  src/components/myPage/MyInfo/index.tsx
Labels: 🛠 Fix

#242 해당 크리에이터 추천 안할 시 카드 UI 변경 안되도록 수정
  src/components/cardItem/content/banner/bannerAvatar/index.tsx
  src/components/cardItem/content/cardBottom/index.tsx
  src/components/cardItem/content/notRecommend/index.tsx
  src/components/cardItem/content/notRecommend/style.css.ts
Labels: 🛠 Fix

#245 회사이메일 인증 로고 안 받도록 수정
  src/__mocks__/handlers/companies.ts
  src/api/companies.ts
  src/components/modal/certification/SendedView/index.tsx
  src/components/modal/certification/SendedView/style.css.ts
Labels: ☀ Feature

#246 크리에이터 이미지 잘리는 버그 수정
  src/components/common/avatar/index.tsx
  src/components/common/avatar/style.css.ts
Labels: 🛠 Fix

#248 비회원일 경우 추천 크리에이터 문구 표시
  src/components/common/slider/index.tsx
  src/components/common/slider/style.css.ts
  src/pages/home/index.tsx
  src/pages/home/style.css.ts
Labels: 🔨 Refactor

#250 회원가입 탭 삭제
  src/components/cardItem/creator/index.tsx
  src/pages/signup/index.tsx
Labels: 🔨 Refactor

#254 데일리 브리핑 도넛 차트 크기 수정
  src/components/dailyBriefing/CategoryChart.tsx
Labels: 🛠 Fix

#255 404 에러 문제 코드 추가
  vercel.json
Labels: 🛠 Fix

#260 구독 피드 버그 해결
  src/components/common/tab/index.tsx
  src/components/modal/login/index.tsx
Labels: 🛠 Fix, 🐛 Bug

#263 데일리 브리핑 페이지 차트 최솟값 설정
  src/components/dailyBriefing/ContentsCountChart.tsx
Labels: ☀ Feature

#264 refactor: 추천 크리에이터 blur 처리
  src/__mocks__/handlers/recommendedCreators.ts
  src/components/common/slider/style.css.ts
  src/components/recommendedCreators/index.tsx
Labels: 🔨 Refactor

#267 내 정보 모달 관리자 페이지 viewing 버그 해결
  src/components/modal/myInfo/index.tsx
Labels: 리뷰 요청, 🛠 Fix, 🐛 Bug

#270 배너 length 버그
  src/components/cardItem/content/banner/bannerAvatar/index.tsx
  src/components/cardItem/content/banner/bannerText/index.tsx
Labels: 🛠 Fix, 🐛 Bug

#271 검색 버그 해결
  src/components/cardItem/content/cardTop/index.tsx
  src/components/cardItem/content/index.tsx
  src/hooks/infiniteQuery/useSearchContentsInfiniteQuery.ts
  src/stores/searchKeyword.ts
Labels: 🛠 Fix

#273 소속 회사 인증 모달 닫히지 않는 버그 해결
  src/components/myPage/MyInfo/index.tsx
Labels: 🛠 Fix

#275 env example 파일 추가
  .env.example
Labels: 📑 Document

#277 스크롤 전 메인 페이지에 스크롤 툴팁 표시
  src/components/main/index.tsx
  src/components/main/style.css.ts
  src/pages/home/index.tsx
  src/styles/keyframes.css.ts
Labels: 리뷰 요청, ☀ Feature

#278 msw 리팩토링
  src/__mocks__/handlers/bookmark.ts
  src/__mocks__/handlers/creatorList.ts
  src/__mocks__/handlers/like.ts
  src/__mocks__/handlers/mainContents.ts
  src/__mocks__/handlers/notRecommend.ts
  src/__mocks__/handlers/subscribe.ts
  src/__mocks__/handlers/view.ts
  src/api/bookmark.ts
  src/api/like.ts
  src/api/notRecommend.ts
Labels: 🔨 Refactor

#280 스크롤 후 메인 페이지 FAB 추가
  src/components/backToTop/index.tsx
  src/components/common/floatingActionButton/index.tsx
  src/components/common/floatingActionButton/style.css.ts
  src/components/common/index.ts
  src/pages/creatorDetail/index.tsx
  src/pages/creatorList/index.tsx
  src/pages/home/index.tsx
  src/pages/searchResult/index.tsx
  src/utils/scroll.ts
Labels: 리뷰 요청, ☀ Feature

#284 툴팁 추가
  index.html
  src/components/admin/contents/index.tsx
  src/components/admin/creators/index.tsx
  src/components/cardItem/content/cardBottom/index.tsx
  src/components/cardItem/content/cardTop/index.tsx
  src/components/cardItem/creator/index.tsx
  src/components/common/header/userNav/Authorized.tsx
  src/components/common/index.ts
  src/components/common/tooltip/index.tsx
  src/components/common/tooltip/style.css.ts
  src/components/common/tooltip/tooltipBox.tsx
  src/components/common/tooltip/tooltipPortal.tsx
  src/styles/keyframes.css.ts
  src/types/positions.ts
  src/utils/coordinates.ts
Labels: 리뷰 요청, ☀ Feature

#283 콘텐츠 회사 추천 배너 컴포넌트 공통화
  src/components/cardItem/content/banner/bannerAvatar/index.tsx
  src/components/cardItem/content/banner/bannerAvatar/style.css.ts
  src/components/cardItem/content/banner/bannerText/index.tsx
  src/components/cardItem/content/banner/bannerText/style.css.ts
  src/components/cardItem/content/cardBottom/index.tsx
  src/components/cardItem/content/recommendationBanner/index.tsx
  src/components/cardItem/content/recommendationBanner/style.css.ts
Labels: 🔨 Refactor
