Repository prgrms-web-devcourse/Team-JJINSA-HyperLink-FE, pull requests merged in 2023-02, with the labels that each got.

#7 design: vanilla extract css 정의
  index.html
  package-lock.json
  src/App.tsx
  src/main.tsx
  src/router.tsx
  src/styles/.gitkeep
  src/styles/global.css.ts
  src/styles/medias.css.ts
  src/styles/tokens.css.ts
  src/styles/utils.css.ts
  src/styles/variants.css.ts
  yarn.lock
Labels: 리뷰 요청, 🎨 Design

#9 아이콘 공통 컴포넌트 구현 및 storybook 연동
  .storybook/main.cjs
  .storybook/preview.cjs
  index.html
  package-lock.json
  package.json
  src/components/common/icon/index.tsx
  src/stories/components/common/Icon.stories.tsx
  src/styles/global.css.ts
  yarn.lock
Labels: 리뷰 요청, ☀ Feature

#13 텍스트 컴포넌트 구현 및 storybook 연동
  src/components/common/icon/index.tsx
  src/components/common/icon/style.css.ts
  src/components/common/text/index.tsx
  src/components/common/text/style.css.ts
  src/stories/components/common/Icon.stories.tsx
  src/stories/components/common/Text.stories.tsx
  src/styles/global.css.ts
  src/styles/variants.css.ts
Labels: 리뷰 요청, ☀ Feature, 🔨 Refactor

#15 헤딩 컴포넌트 구현 및 storybook 연동
  src/components/common/header/index.tsx
  src/components/common/heading/index.tsx
  src/components/common/heading/style.css.ts
  src/components/common/index.ts
  src/stories/components/common/Header.stories.tsx
Labels: 리뷰 요청, ☀ Feature

#17 storybook global css 적용되지 않는 문제
  .storybook/preview.cjs
Labels: 리뷰 요청, 🛠 Fix

#22 favicon 변경
  index.html
  src/assets/favicon.ico
Labels: ⚙ Etc

#23 스피너 컴포넌트 구현 및 storybook 연동
  src/components/common/icon/index.tsx
  src/components/common/icon/style.css.ts
  src/components/common/spinner/index.tsx
  src/stories/components/common/Icon.stories.tsx
  src/stories/components/common/Spinner.stories.tsx
  src/styles/variants.css.ts
Labels: ☀ Feature

#24 divider 컴포넌트 구현 및 storybook 연동
  src/components/common/divider/index.tsx
  src/components/common/divider/style.css.ts
  src/stories/components/common/Divider.stories.tsx
Labels: 리뷰 요청, ☀ Feature

#30 input 컴포넌트 구현 및 storybook 연동
  src/components/common/input/index.tsx
  src/components/common/input/style.css.ts
  src/hooks/.gitkeep
  src/hooks/useInput.ts
  src/stories/components/common/Input.stories.tsx
  src/styles/global.css.ts
  src/styles/variants.css.ts
Labels: 리뷰 요청, ☀ Feature

#35 slider 컴포넌트 구현 및 storybook 연동
  src/components/common/slider/index.tsx
  src/components/common/slider/style.css.ts
  src/stories/components/common/Slider.stories.tsx
Labels: 리뷰 요청, ☀ Feature

#28 modal 컴포넌트 구현 및 storybook 연동
  src/components/common/modal/ModalPortal.tsx
  src/components/common/modal/index.tsx
  src/components/common/modal/style.css.ts
  src/hooks/useClickAway.ts
  src/stories/components/common/Modal.stories.tsx
Labels: 리뷰 요청, ☀ Feature

#40 chore: recoil, react-query, react-query-devtools 설정
  src/main.tsx
Labels: 리뷰 요청, 👩‍🌾 Chore

#44 헤더, 네비게이션 UI 구현
  src/App.tsx
  src/assets/logo.svg
  src/assets/user.svg
  src/components/common/badge/index.tsx
  src/components/common/badge/style.css.ts
  src/components/common/button/index.tsx
  src/components/common/button/style.css.ts
  src/components/common/header/SearchBar.tsx
  src/components/common/header/UserNav.tsx
  src/components/common/header/index.tsx
  src/components/common/header/style.css.ts
  src/components/common/icon/style.css.ts
  src/components/common/input/index.tsx
  src/components/common/input/style.css.ts
  src/components/common/tab/index.css.ts
  src/components/layout/index.tsx
  src/main.tsx
Labels: 리뷰 요청, ☀ Feature, 🎨 Design

#47 로그인 ui 구현
  .gitignore
  package.json
  src/App.tsx
  src/assets/googleLogo.png
  src/components/common/button/index.tsx
  src/components/common/button/style.css.ts
  src/components/common/dropdown/index.tsx
  src/components/common/dropdown/style.css.ts
  src/components/common/input/index.tsx
  src/components/common/input/style.css.ts
  src/components/common/text/index.tsx
  src/components/modal/index.ts
  src/components/modal/login/index.tsx
  src/components/modal/login/style.css.ts
  src/components/signup/basicInfo.tsx
  src/components/signup/categoryInfo.tsx
  src/components/signup/index.ts
  src/components/signup/style.css.ts
  src/components/signup/workInfo.tsx
  src/hooks/useDropdown.ts
  src/main.tsx
  src/pages/home.tsx
  src/pages/index.ts
  src/pages/sigunup/index.tsx
  src/pages/sigunup/style.css.ts
  src/stories/components/common/Avatar.stories.tsx
  src/stories/components/common/Badge.stories.tsx
  src/stories/components/common/Button.stories.tsx
  src/stories/components/common/Divider.stories.tsx
  src/stories/components/common/Dropdown.stories.tsx
  src/stories/components/common/Header.stories.tsx
  src/stories/components/common/Icon.stories.tsx
  src/stories/components/common/Image.stories.tsx
  src/stories/components/common/Input.stories.tsx
  src/stories/components/common/Modal.stories.tsx
  src/stories/components/common/Slider.stories.tsx
  src/stories/components/common/Spinner.stories.tsx
  src/stories/components/common/Tab.stories.tsx
  src/stories/components/common/Text.stories.tsx
  src/stories/components/modal/login.stories.tsx
  src/styles/tokens.css.ts
  yarn.lock
Labels: 리뷰 요청, 🎨 Design

#51 파일명 대문자 변경
  src/components/signup/BasicInfo.tsx
  src/components/signup/CategoryInfo.tsx
  src/components/signup/WorkInfo.tsx
Labels: 📁 Rename

#46 크리에이터, 아티클 카드 UI 구현
  src/components/cardItem/article/CardBottom.css.ts
  src/components/cardItem/article/CardBottom.tsx
  src/components/cardItem/article/CardModal.tsx
  src/components/cardItem/article/CardTop.css.ts
  src/components/cardItem/article/CardTop.tsx
  src/components/cardItem/article/index.tsx
  src/components/cardItem/article/style.css.ts
  src/components/cardItem/creater/index.tsx
  src/components/cardItem/creater/style.css.ts
Labels: 🎨 Design

#52 variants 종류 별 분할
  src/components/common/badge/style.css.ts
  src/components/common/button/style.css.ts
  src/components/common/divider/style.css.ts
  src/components/common/dropdown/index.tsx
  src/components/common/dropdown/style.css.ts
  src/components/common/header/style.css.ts
  src/components/common/heading/index.tsx
  src/components/common/icon/index.tsx
  src/components/common/icon/style.css.ts
  src/components/common/input/style.css.ts
  src/components/common/modal/style.css.ts
  src/components/common/slider/style.css.ts
  src/components/common/spinner/index.tsx
  src/components/common/tab/index.tsx
  src/components/common/tab/style.css.ts
  src/components/common/text/style.css.ts
  src/components/modal/login/index.tsx
  src/components/modal/login/style.css.ts
  src/components/signup/CategoryInfo.tsx
  src/components/signup/categoryInfo.tsx
  src/pages/sigunup/index.tsx
  src/pages/sigunup/style.css.ts
  src/stories/components/common/Header.stories.tsx
  src/stories/components/common/Icon.stories.tsx
  src/stories/components/common/Spinner.stories.tsx
  src/styles/global.css.ts
  src/styles/utils.css.ts
  src/styles/variants.css.ts
Labels: 🔨 Refactor

#54 소문자 파일 제거
  src/components/signup/basicInfo.tsx
  src/components/signup/categoryInfo.tsx
  src/components/signup/workInfo.tsx
Labels: 📁 Rename, 🗑 Remove

#58 로그인 버튼 연동
  src/components/common/header/UserNav.tsx
  src/components/layout/index.tsx
  src/stores/.gitkeep
  src/stores/atoms.ts
Labels: ☀ Feature

#61 카운트다운 시간 버그 해결
  src/components/common/header/CountDown.tsx
  src/components/common/header/index.tsx
Labels: 리뷰 요청, 🛠 Fix

#60 회원 가입 정보 입력 페이지 애니메이션
  src/components/signup/BasicInfo.tsx
  src/components/signup/CategoryInfo.tsx
  src/components/signup/WorkInfo.tsx
  src/components/signup/style.css.ts
  src/pages/sigunup/index.tsx
  src/styles/keyframes.css.ts
Labels: ☀ Feature

#56 axios instance 생성 및 interceptor 추가
  src/api/.gitkeep
  src/api/core.ts
Labels: 리뷰 요청, ☀ Feature

#64 추천 회사 배너 애니메이션 기능 구현
  src/components/cardItem/article/banner/BannerAvatar.css.ts
  src/components/cardItem/article/banner/BannerAvatar.tsx
  src/components/cardItem/article/banner/BannerText.css.ts
  src/components/cardItem/article/banner/BannerText.tsx
  src/components/cardItem/article/cardBottom/index.tsx
  src/components/cardItem/article/cardBottom/style.css.ts
  src/components/cardItem/article/cardTop/index.tsx
  src/components/cardItem/article/cardTop/style.css.ts
  src/components/cardItem/article/index.tsx
  src/components/cardItem/article/style.css.ts
  src/components/cardItem/creater/style.css.ts
  src/components/common/card/style.css.ts
Labels: ☀ Feature
